import type { ItemDefinition, ItemId } from '@extract/game-types';
import { SEASON_1 } from './season';

type ItemInput = Omit<ItemDefinition, 'seasonId' | 'maxSupply' | 'metadata'> &
  Partial<Pick<ItemDefinition, 'seasonId' | 'maxSupply' | 'metadata'>>;

const item = (def: ItemInput): ItemDefinition => ({
  seasonId: null,
  maxSupply: null,
  metadata: {},
  ...def,
});

/**
 * Item catalog. Values are integer cents of TEST USDC.
 * This file is the source of truth; `pnpm db:seed` mirrors it into ItemDefinition.
 */
export const ITEM_DEFINITIONS: readonly ItemDefinition[] = [
  // --- Weapons -------------------------------------------------------------
  item({
    id: 'basic_pistol',
    name: 'Basic Pistol',
    type: 'WEAPON',
    rarity: 'COMMON',
    stackable: false,
    maxStack: 1,
    estimatedValue: 0,
    icon: 'pistol',
    persistable: false,
    dropWeight: 0,
    dropQuantity: [1, 1],
    metadata: { weaponId: 'basic_pistol', starter: true, description: 'Weak starter sidearm.' },
  }),
  item({
    id: 'smg',
    name: 'SMG',
    type: 'WEAPON',
    rarity: 'RARE',
    stackable: false,
    maxStack: 1,
    estimatedValue: 250,
    icon: 'smg',
    persistable: true,
    dropWeight: 5,
    dropQuantity: [1, 1],
    metadata: { weaponId: 'smg', description: 'Very high fire rate, low damage.' },
  }),
  item({
    id: 'shotgun',
    name: 'Shotgun',
    type: 'WEAPON',
    rarity: 'RARE',
    stackable: false,
    maxStack: 1,
    estimatedValue: 300,
    icon: 'shotgun',
    persistable: true,
    dropWeight: 4,
    dropQuantity: [1, 1],
    metadata: { weaponId: 'shotgun', description: 'Devastating at close range.' },
  }),
  item({
    id: 'assault_rifle',
    name: 'Assault Rifle',
    type: 'WEAPON',
    rarity: 'EPIC',
    stackable: false,
    maxStack: 1,
    estimatedValue: 600,
    icon: 'rifle',
    persistable: true,
    dropWeight: 6,
    dropQuantity: [1, 1],
    metadata: { weaponId: 'assault_rifle', description: 'Reliable mid-range rifle.' },
  }),
  // --- Ammo ----------------------------------------------------------------
  item({
    id: 'ammo_light',
    name: 'Light Ammo',
    type: 'AMMO',
    rarity: 'COMMON',
    stackable: true,
    maxStack: 240,
    estimatedValue: 0,
    icon: 'ammo_light',
    persistable: false,
    dropWeight: 6,
    dropQuantity: [18, 36],
    metadata: { ammoType: 'light', description: 'Pistol & SMG ammunition.' },
  }),
  item({
    id: 'ammo_rifle',
    name: 'Rifle Ammo',
    type: 'AMMO',
    rarity: 'COMMON',
    stackable: true,
    maxStack: 200,
    estimatedValue: 0,
    icon: 'ammo_rifle',
    persistable: false,
    dropWeight: 4,
    dropQuantity: [15, 30],
    metadata: { ammoType: 'rifle', description: 'Assault rifle ammunition.' },
  }),
  item({
    id: 'ammo_shell',
    name: 'Shotgun Shells',
    type: 'AMMO',
    rarity: 'COMMON',
    stackable: true,
    maxStack: 60,
    estimatedValue: 0,
    icon: 'ammo_shell',
    persistable: false,
    dropWeight: 3,
    dropQuantity: [6, 12],
    metadata: { ammoType: 'shell', description: 'Shotgun shells.' },
  }),
  // --- Consumables ---------------------------------------------------------
  item({
    id: 'medkit',
    name: 'Medkit',
    type: 'CONSUMABLE',
    rarity: 'COMMON',
    stackable: true,
    maxStack: 5,
    estimatedValue: 40,
    icon: 'medkit',
    persistable: true,
    dropWeight: 5,
    dropQuantity: [1, 2],
    metadata: { heal: 50, useTimeMs: 1500, description: 'Restores 50 health.' },
  }),
  item({
    id: 'armor_plate',
    name: 'Armor Plate',
    type: 'CONSUMABLE',
    rarity: 'RARE',
    stackable: true,
    maxStack: 5,
    estimatedValue: 90,
    icon: 'armor',
    persistable: true,
    dropWeight: 6,
    dropQuantity: [1, 2],
    metadata: { armor: 25, useTimeMs: 1000, description: 'Adds 25 armor.' },
  }),
  // --- Valuables -----------------------------------------------------------
  item({
    id: 'scrap',
    name: 'Scrap',
    type: 'VALUABLE',
    rarity: 'COMMON',
    stackable: true,
    maxStack: 50,
    estimatedValue: 5,
    icon: 'scrap',
    persistable: true,
    dropWeight: 10,
    dropQuantity: [2, 6],
    metadata: { description: 'Bits of metal. Worth a little.' },
  }),
  item({
    id: 'copper_wire',
    name: 'Copper Wire',
    type: 'VALUABLE',
    rarity: 'COMMON',
    stackable: true,
    maxStack: 20,
    estimatedValue: 15,
    icon: 'wire',
    persistable: true,
    dropWeight: 6,
    dropQuantity: [1, 3],
    metadata: { description: 'Salvaged copper.' },
  }),
  item({
    id: 'circuit_board',
    name: 'Circuit Board',
    type: 'VALUABLE',
    rarity: 'RARE',
    stackable: true,
    maxStack: 10,
    estimatedValue: 120,
    icon: 'circuit',
    persistable: true,
    dropWeight: 5,
    dropQuantity: [1, 2],
    metadata: { description: 'Salvageable electronics.' },
  }),
  item({
    id: 'gold_bar',
    name: 'Gold Bar',
    type: 'VALUABLE',
    rarity: 'EPIC',
    stackable: true,
    maxStack: 3,
    estimatedValue: 650,
    icon: 'gold',
    persistable: true,
    dropWeight: 4,
    dropQuantity: [1, 1],
    metadata: { description: 'Heavy. Shiny. Valuable.' },
  }),
  item({
    id: 'quantum_core',
    name: 'Quantum Core',
    type: 'VALUABLE',
    rarity: 'LEGENDARY',
    stackable: false,
    maxStack: 1,
    estimatedValue: 3000,
    icon: 'core',
    persistable: true,
    dropWeight: 3,
    dropQuantity: [1, 1],
    metadata: { description: 'Experimental power core.' },
  }),
  // --- Cosmetics -----------------------------------------------------------
  item({
    id: 'rare_skin_fragment',
    name: 'Rare Skin Fragment',
    type: 'COSMETIC',
    rarity: 'RARE',
    stackable: true,
    maxStack: 10,
    estimatedValue: 150,
    icon: 'fragment',
    persistable: true,
    dropWeight: 4,
    dropQuantity: [1, 1],
    metadata: { description: 'Combine fragments into skins (future).' },
  }),
  item({
    id: 'epic_weapon_skin',
    name: 'Epic Weapon Skin',
    type: 'COSMETIC',
    rarity: 'EPIC',
    stackable: false,
    maxStack: 1,
    estimatedValue: 900,
    icon: 'skin',
    persistable: true,
    dropWeight: 3,
    dropQuantity: [1, 1],
    metadata: { description: 'Neon Viper weapon finish.' },
  }),
  item({
    id: 'cyber_katana',
    name: 'Cyber Katana',
    type: 'COSMETIC',
    rarity: 'LEGENDARY',
    stackable: false,
    maxStack: 1,
    estimatedValue: 4280,
    icon: 'katana',
    persistable: true,
    dropWeight: 2,
    dropQuantity: [1, 1],
    metadata: { description: 'Legendary katana cosmetic.' },
  }),
  item({
    id: 'genesis_crown',
    name: 'Genesis Crown',
    type: 'COSMETIC',
    rarity: 'MYTHIC',
    stackable: false,
    maxStack: 1,
    estimatedValue: 25000,
    icon: 'crown',
    persistable: true,
    dropWeight: 1,
    dropQuantity: [1, 1],
    seasonId: SEASON_1.id,
    maxSupply: SEASON_1.genesisCrownSupply,
    metadata: { limited: true, description: 'Season 1 limited edition. Serial numbered.' },
  }),
];

export const ITEMS: Readonly<Record<ItemId, ItemDefinition>> = Object.freeze(
  Object.fromEntries(ITEM_DEFINITIONS.map((d) => [d.id, d])),
);

export function getItemDef(id: ItemId): ItemDefinition {
  const def = ITEMS[id];
  if (!def) throw new Error(`Unknown item id: ${id}`);
  return def;
}

export function isItemId(id: unknown): id is ItemId {
  return typeof id === 'string' && Object.prototype.hasOwnProperty.call(ITEMS, id);
}

export const STARTER_WEAPON_ITEM = 'basic_pistol';
